steps:
  # 1. Construir la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/solar-service", "."]

  # 2. Subir la imagen al Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/solar-service"]

  # 3. Desplegar en Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "solar-service",
        "--image",
        "gcr.io/$PROJECT_ID/solar-service",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

images:
  - gcr.io/$PROJECT_ID/solar-service
